### PR TITLE
Make the case study dropdowns clickable

### PR DESCRIPTION
**Pull request by lhr-git**
### Description

List of proposed changes:

- Made the case study dropdowns clickable

### Additional Notes

### CODE REVIEW

**Comment by Fbasham** [comment]
The hover state (in mobile view) and focus state (mobile and desktop) have this ellipse shape:

image

**Comment by lhr-git** [comment]
> 

Would you prefer it rectangular?

**Comment by Fbasham** [comment]
> > 
> 
> Would you prefer it rectangular?

I'd personally make it more rectangular.  This is happening because of the MUI ripple effect. You can hopefully see some fixes here as a start:  https://stackoverflow.com/questions/54296070/material-ui-icon-button-highlights-with-an-elliptical-background-when-cursor-is

**Comment by lhr-git** [comment]
oh, I figured out this fix for it yesterday. I'll take a look at SO now though.

**Review by Fbasham — APPROVED** [review]

**Pull request merged**
